Repository Cushion-Dev/Cushion-BE, pull requests merged in 2024-07, with the labels that each got.

#5 [Swagger] API 명세서 초안 작성
  build.gradle
  src/main/java/com/chzzk/cushion/chatroom/application/ChatRoomService.java
  src/main/java/com/chzzk/cushion/chatroom/application/SearchChatRoomService.java
  src/main/java/com/chzzk/cushion/chatroom/domain/Relationship.java
  src/main/java/com/chzzk/cushion/chatroom/domain/SenderType.java
  src/main/java/com/chzzk/cushion/chatroom/dto/ChatRoomDetailResponse.java
  src/main/java/com/chzzk/cushion/chatroom/dto/ChatRoomRequest.java
  src/main/java/com/chzzk/cushion/chatroom/dto/ChatRoomResponse.java
  src/main/java/com/chzzk/cushion/chatroom/dto/MessageDto.java
  src/main/java/com/chzzk/cushion/chatroom/dto/SearchWordAutoCompleteResponse.java
  src/main/java/com/chzzk/cushion/chatroom/presentation/ChatRoomController.java
  src/main/java/com/chzzk/cushion/chatroom/presentation/SearchChatRoomController.java
  src/main/java/com/chzzk/cushion/style/application/ChangeStyleService.java
  src/main/java/com/chzzk/cushion/style/presentation/ChangeStyleController.java
  src/main/resources/application-dev.yml
Labels: ⚙️ chore

#6 소셜 로그인 기능 구현 완료
  build.gradle
  src/main/java/com/chzzk/cushion/global/config/SecurityConfig.java
  src/main/java/com/chzzk/cushion/global/exception/CushionException.java
  src/main/java/com/chzzk/cushion/global/exception/ErrorCode.java
  src/main/java/com/chzzk/cushion/global/exception/ErrorResponse.java
  src/main/java/com/chzzk/cushion/global/exception/GlobalExceptionHandler.java
  src/main/java/com/chzzk/cushion/global/jwt/ApiMemberArgumentResolver.java
  src/main/java/com/chzzk/cushion/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/chzzk/cushion/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/chzzk/cushion/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/chzzk/cushion/global/jwt/JwtTokenProvider.java
  src/main/java/com/chzzk/cushion/global/oauth2/CustomSuccessHandler.java
  src/main/java/com/chzzk/cushion/global/oauth2/dto/CustomOAuth2User.java
  src/main/java/com/chzzk/cushion/global/oauth2/dto/GoogleResponse.java
  src/main/java/com/chzzk/cushion/global/oauth2/dto/KakaoResponse.java
  src/main/java/com/chzzk/cushion/global/oauth2/dto/NaverResponse.java
  src/main/java/com/chzzk/cushion/global/oauth2/dto/Oauth2Dto.java
  src/main/java/com/chzzk/cushion/global/oauth2/dto/Oauth2Response.java
  src/main/java/com/chzzk/cushion/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/chzzk/cushion/global/utils/AuthPrincipal.java
  src/main/java/com/chzzk/cushion/member/application/MyUserDetailService.java
  src/main/java/com/chzzk/cushion/member/domain/CustomUserDetails.java
  src/main/java/com/chzzk/cushion/member/domain/Member.java
  src/main/java/com/chzzk/cushion/member/domain/MemberRepository.java
  src/main/java/com/chzzk/cushion/member/dto/ApiMember.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ feature, ⚙️ chore

#9 로그아웃 기능 구현 완료
  src/main/java/com/chzzk/cushion/global/config/SecurityConfig.java
  src/main/java/com/chzzk/cushion/global/exception/ErrorCode.java
  src/main/java/com/chzzk/cushion/member/application/MemberService.java
  src/main/java/com/chzzk/cushion/member/presentation/MemberController.java
Labels: ✨ feature

#13 fix: 서버에서 로그아웃 시 쿠키 넘어오지 않는 에러 해결
  src/main/java/com/chzzk/cushion/global/config/SecurityConfig.java
  src/main/java/com/chzzk/cushion/global/jwt/JwtTokenProvider.java
Labels: 🛠️ fix

#15 문체 변환 기능 구현
  build.gradle
  src/main/java/com/chzzk/cushion/style/application/ChangeStyleService.java
  src/main/java/com/chzzk/cushion/style/domain/ClovaStudioApiExecutor.java
  src/main/java/com/chzzk/cushion/style/presentation/ChangeStyleController.java
  src/main/resources/application.yml
Labels: ✨ feature

#21 소셜 로그인 후 타 API에서 회원 미인증 문제 해결 완료
  src/main/java/com/chzzk/cushion/global/config/WebConfig.java
  src/main/java/com/chzzk/cushion/global/jwt/ApiMemberArgumentResolver.java
  src/main/java/com/chzzk/cushion/global/jwt/JwtTokenProvider.java
  src/main/java/com/chzzk/cushion/global/oauth2/dto/CustomOAuth2User.java
  src/main/java/com/chzzk/cushion/member/application/MyUserDetailService.java
  src/main/java/com/chzzk/cushion/member/domain/Member.java
  src/main/java/com/chzzk/cushion/member/dto/ApiMember.java
Labels: 🛠️ fix

#19 채팅방 목록 조회 및 검색 기능 구현
  build.gradle
  src/main/java/com/chzzk/cushion/CushionApplication.java
  src/main/java/com/chzzk/cushion/chatroom/application/ChatRoomService.java
  src/main/java/com/chzzk/cushion/chatroom/application/SearchChatRoomService.java
  src/main/java/com/chzzk/cushion/chatroom/domain/ChatRoom.java
  src/main/java/com/chzzk/cushion/chatroom/domain/repository/ChatRoomRepository.java
  src/main/java/com/chzzk/cushion/chatroom/domain/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/chzzk/cushion/chatroom/domain/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/chzzk/cushion/chatroom/dto/ChatRoomResponse.java
  src/main/java/com/chzzk/cushion/chatroom/dto/SearchWordAutoCompleteResponse.java
  src/main/java/com/chzzk/cushion/chatroom/presentation/SearchChatRoomController.java
  src/main/java/com/chzzk/cushion/global/config/QuerydslConfig.java
Labels: ✨ feature

#22 사용자 설정 기능 구현 완료
  src/main/java/com/chzzk/cushion/member/application/MemberService.java
  src/main/java/com/chzzk/cushion/member/domain/Member.java
  src/main/java/com/chzzk/cushion/member/dto/MemberDto.java
  src/main/java/com/chzzk/cushion/member/presentation/MemberController.java
Labels: ✨ feature

#25 사용자 설정 수정 기능, 회원 탈퇴 기능 구현 완료
  src/main/java/com/chzzk/cushion/member/application/MemberService.java
  src/main/java/com/chzzk/cushion/member/presentation/MemberController.java
Labels: ✨ feature

#27 채팅방 생성 기능 구현 완료
  src/main/java/com/chzzk/cushion/chatroom/application/ChatRoomService.java
  src/main/java/com/chzzk/cushion/chatroom/domain/ChatRoom.java
  src/main/java/com/chzzk/cushion/chatroom/domain/Relationship.java
  src/main/java/com/chzzk/cushion/chatroom/dto/ChatRoomRequest.java
  src/main/java/com/chzzk/cushion/chatroom/presentation/ChatRoomController.java
  src/main/java/com/chzzk/cushion/global/exception/ErrorCode.java
Labels: ✨ feature

#29 채팅방 다중 삭제 기능 구현 완료
  src/main/java/com/chzzk/cushion/chatroom/application/ChatRoomService.java
  src/main/java/com/chzzk/cushion/chatroom/domain/repository/ChatRoomRepository.java
  src/main/java/com/chzzk/cushion/chatroom/dto/ChatRoomRequest.java
  src/main/java/com/chzzk/cushion/chatroom/presentation/ChatRoomController.java
  src/main/java/com/chzzk/cushion/global/exception/ErrorCode.java
  src/main/java/com/chzzk/cushion/member/domain/Member.java
Labels: ✨ feature

#35 ApiMember 컨트롤러 부분 hidden 처리 완료
  src/main/java/com/chzzk/cushion/chatroom/presentation/ChatRoomController.java
  src/main/java/com/chzzk/cushion/member/presentation/MemberController.java
  src/main/java/com/chzzk/cushion/style/presentation/ChangeStyleController.java
Labels: ✨ feature

#38 CORS 에러 해결 위한 URL 허용
  src/main/java/com/chzzk/cushion/global/config/SecurityConfig.java
Labels: ✨ feature

#37 문체 변환, 채팅방 목록 조회, 채팅방 검색 기능 구현 완료
  src/main/java/com/chzzk/cushion/chatroom/application/ChatRoomService.java
  src/main/java/com/chzzk/cushion/chatroom/application/SearchChatRoomService.java
  src/main/java/com/chzzk/cushion/chatroom/domain/ChatRoom.java
  src/main/java/com/chzzk/cushion/chatroom/domain/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/chzzk/cushion/chatroom/domain/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/chzzk/cushion/chatroom/domain/repository/MessageRepository.java
  src/main/java/com/chzzk/cushion/chatroom/dto/ChatRoomResponse.java
  src/main/java/com/chzzk/cushion/chatroom/presentation/ChatRoomController.java
  src/main/java/com/chzzk/cushion/chatroom/presentation/SearchChatRoomController.java
  src/main/java/com/chzzk/cushion/style/application/ChangeStyleService.java
Labels: ✨ feature

#47 OCR 관련 API 개발
  src/main/java/com/chzzk/cushion/style/application/ChangeStyleService.java
  src/main/java/com/chzzk/cushion/style/application/ExtractConversationTextWithOcrService.java
  src/main/java/com/chzzk/cushion/style/domain/ClovaApiRequestDataGenerator.java
  src/main/java/com/chzzk/cushion/style/domain/ClovaOcrApiExecutor.java
  src/main/java/com/chzzk/cushion/style/domain/ClovaStudioApiExecutor.java
  src/main/java/com/chzzk/cushion/style/dto/ImageParsingRequest.java
  src/main/java/com/chzzk/cushion/style/dto/OcrImageDto.java
  src/main/java/com/chzzk/cushion/style/presentation/ExtractConversationTextWithOcrController.java
  src/main/resources/application.yml
Labels: ✨ feature

#48 JWT 예외처리, 로그인 성공시 리다이렉트 URL 변경, 채팅방 생성시 응답 반환
  src/main/java/com/chzzk/cushion/chatroom/application/ChatRoomService.java
  src/main/java/com/chzzk/cushion/chatroom/dto/ChatRoomResponse.java
  src/main/java/com/chzzk/cushion/chatroom/presentation/ChatRoomController.java
  src/main/java/com/chzzk/cushion/global/jwt/JwtTokenProvider.java
  src/main/java/com/chzzk/cushion/global/oauth2/CustomSuccessHandler.java
  src/main/java/com/chzzk/cushion/global/oauth2/dto/CustomOAuth2User.java
  src/main/java/com/chzzk/cushion/global/oauth2/service/CustomOAuth2UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: ✨ feature

#51 채팅방 메시지에 cascade 적용
  src/main/java/com/chzzk/cushion/chatroom/domain/ChatRoom.java
Labels: 🛠️ fix

#52 성격 분석 기능 구현 마무리
  src/main/java/com/chzzk/cushion/chatroom/domain/Message.java
  src/main/java/com/chzzk/cushion/member/domain/Member.java
  src/main/java/com/chzzk/cushion/style/application/AnalyzeCharacteristicsService.java
  src/main/java/com/chzzk/cushion/style/application/ChangeStyleService.java
  src/main/java/com/chzzk/cushion/style/application/ExtractConversationTextWithOcrService.java
  src/main/java/com/chzzk/cushion/style/domain/ClovaApiRequestDataGenerator.java
  src/main/java/com/chzzk/cushion/style/domain/ClovaStudioApiExecutor.java
  src/main/java/com/chzzk/cushion/style/dto/ChangeStyleRequest.java
  src/main/java/com/chzzk/cushion/style/dto/ImageParsingRequest.java
  src/main/java/com/chzzk/cushion/style/dto/OcrImageDto.java
  src/main/java/com/chzzk/cushion/style/presentation/AnalyzeCharacteristicsServiceController.java
  src/main/java/com/chzzk/cushion/style/presentation/ChangeStyleController.java
  src/main/java/com/chzzk/cushion/style/presentation/ExtractConversationTextWithOcrController.java
Labels: ✨ feature

#55 상대방 성격을 이용한 문체 변환 기능 구현
  src/main/java/com/chzzk/cushion/style/application/ChangeStyleService.java
  src/main/java/com/chzzk/cushion/style/domain/ClovaApiRequestDataGenerator.java
  src/main/java/com/chzzk/cushion/style/dto/ChangeStyleWithCharacteristicsRequest.java
  src/main/java/com/chzzk/cushion/style/presentation/ChangeStyleController.java
Labels: ✨ feature

#57 OCR 텍스트 추출 로직과 성격 분석 로직 분리
  src/main/java/com/chzzk/cushion/style/application/AnalyzeCharacteristicsService.java
  src/main/java/com/chzzk/cushion/style/application/ExtractConversationService.java
  src/main/java/com/chzzk/cushion/style/dto/AnalyzeCharacteristicsRequest.java
  src/main/java/com/chzzk/cushion/style/presentation/AnalyzeCharacteristicsServiceController.java
  src/main/java/com/chzzk/cushion/style/presentation/ExtractConversationController.java
Labels: ✨ feature, 🪄 refactor

#60 더 많은 이미지 확장자 지원
  src/main/java/com/chzzk/cushion/style/domain/ClovaOcrApiExecutor.java
Labels: 🛠️ fix

#62 클로바 관련 API의 Swagger 설명 수정
  src/main/java/com/chzzk/cushion/style/presentation/AnalyzeCharacteristicsServiceController.java
  src/main/java/com/chzzk/cushion/style/presentation/ChangeStyleController.java
  src/main/java/com/chzzk/cushion/style/presentation/ExtractConversationController.java
Labels: ⚙️ chore

#65 중복 이메일 등록 시 에러 해결 완료
  src/main/java/com/chzzk/cushion/global/jwt/ApiMemberArgumentResolver.java
  src/main/java/com/chzzk/cushion/global/jwt/JwtTokenProvider.java
  src/main/java/com/chzzk/cushion/member/application/MyUserDetailService.java
  src/main/java/com/chzzk/cushion/member/domain/MemberRepository.java
  src/main/java/com/chzzk/cushion/member/dto/ApiMember.java
Labels: ✨ feature

#63 CLOVA 관련 정보 환경변수로 변경
  src/main/resources/application.yml
Labels: ⚙️ chore

#68 채팅방 생성 후 응답 변경
  src/main/java/com/chzzk/cushion/chatroom/application/ChatRoomService.java
  src/main/java/com/chzzk/cushion/chatroom/dto/ChatRoomResponse.java
  src/main/java/com/chzzk/cushion/chatroom/presentation/ChatRoomController.java
  src/main/resources/application.yml
Labels: ✨ feature

#66 이미지 업로드 관련 예외처리 로직 추가
  src/main/java/com/chzzk/cushion/global/exception/ErrorCode.java
  src/main/java/com/chzzk/cushion/global/exception/GlobalExceptionHandler.java
  src/main/java/com/chzzk/cushion/style/domain/ClovaOcrApiExecutor.java
  src/main/java/com/chzzk/cushion/style/presentation/ExtractConversationController.java
Labels: ✨ feature

#74 검증 어노테이션 추가
  src/main/java/com/chzzk/cushion/chatroom/dto/ChatRoomRequest.java
  src/main/java/com/chzzk/cushion/chatroom/presentation/ChatRoomController.java
  src/main/java/com/chzzk/cushion/member/dto/MemberDto.java
  src/main/java/com/chzzk/cushion/member/presentation/MemberController.java
  src/main/java/com/chzzk/cushion/style/dto/AnalyzeCharacteristicsRequest.java
  src/main/java/com/chzzk/cushion/style/dto/ChangeStyleRequest.java
  src/main/java/com/chzzk/cushion/style/dto/ChangeStyleWithCharacteristicsRequest.java
  src/main/java/com/chzzk/cushion/style/presentation/AnalyzeCharacteristicsServiceController.java
  src/main/java/com/chzzk/cushion/style/presentation/ChangeStyleController.java
Labels: ✨ feature

#76 채팅방 수정 시 제목에 관계의 라벨이 포함되도록 수정
  src/main/java/com/chzzk/cushion/chatroom/application/ChatRoomService.java
  src/main/java/com/chzzk/cushion/chatroom/domain/ChatRoom.java
Labels: 🪄 refactor, 🛠️ fix

#75 채팅방 상세 조회 시 메시지의 생성일 기준으로 내림차순되도록 구현
  src/main/java/com/chzzk/cushion/chatroom/application/ChatRoomService.java
Labels: 🛠️ fix
